# TCL File Generated by Component Editor 17.1
# Fri Feb 04 11:56:38 CET 2022
# DO NOT MODIFY


# 
# Avalon_Chroma_Process "Avalon_Chroma_Process" v1.0
#  2022.02.04.11:56:38
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Avalon_Chroma_Process
# 
set_module_property DESCRIPTION ""
set_module_property NAME Avalon_Chroma_Process
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP IP
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Avalon_Chroma_Process
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_up_avalon_chroma_key
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ChromaProces.v VERILOG PATH avalon_chroma_key/ChromaProces.v
add_fileset_file altera_up_avalon_chroma_key.v VERILOG PATH avalon_chroma_key/altera_up_avalon_chroma_key.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_up_avalon_chroma_key
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ChromaProces.v VERILOG PATH avalon_chroma_key/ChromaProces.v
add_fileset_file altera_up_avalon_chroma_key.v VERILOG PATH avalon_chroma_key/altera_up_avalon_chroma_key.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_background_sink
# 
add_interface avalon_background_sink avalon_streaming end
set_interface_property avalon_background_sink associatedClock clock
set_interface_property avalon_background_sink associatedReset reset
set_interface_property avalon_background_sink dataBitsPerSymbol 10
set_interface_property avalon_background_sink errorDescriptor ""
set_interface_property avalon_background_sink firstSymbolInHighOrderBits true
set_interface_property avalon_background_sink maxChannel 0
set_interface_property avalon_background_sink readyLatency 0
set_interface_property avalon_background_sink ENABLED true
set_interface_property avalon_background_sink EXPORT_OF ""
set_interface_property avalon_background_sink PORT_NAME_MAP ""
set_interface_property avalon_background_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_background_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_background_sink pixel_fondo data Input 40
add_interface_port avalon_background_sink pixel_fondo_empty empty Input 2
add_interface_port avalon_background_sink pixel_fondo_endofpacket endofpacket Input 1
add_interface_port avalon_background_sink pixel_fondo_ready ready Output 1
add_interface_port avalon_background_sink pixel_fondo_startofpacket startofpacket Input 1
add_interface_port avalon_background_sink pixel_fondo_valid valid Input 1


# 
# connection point avalon_video_sink
# 
add_interface avalon_video_sink avalon_streaming end
set_interface_property avalon_video_sink associatedClock clock
set_interface_property avalon_video_sink associatedReset reset
set_interface_property avalon_video_sink dataBitsPerSymbol 10
set_interface_property avalon_video_sink errorDescriptor ""
set_interface_property avalon_video_sink firstSymbolInHighOrderBits true
set_interface_property avalon_video_sink maxChannel 0
set_interface_property avalon_video_sink readyLatency 0
set_interface_property avalon_video_sink ENABLED true
set_interface_property avalon_video_sink EXPORT_OF ""
set_interface_property avalon_video_sink PORT_NAME_MAP ""
set_interface_property avalon_video_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_video_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_video_sink pixel_video data Input 30
add_interface_port avalon_video_sink pixel_video_empty empty Input 2
add_interface_port avalon_video_sink pixel_video_endofpacket endofpacket Input 1
add_interface_port avalon_video_sink pixel_video_ready ready Output 1
add_interface_port avalon_video_sink pixel_video_startofpacket startofpacket Input 1
add_interface_port avalon_video_sink pixel_video_valid valid Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave chipselect chipselect Input 1
add_interface_port avalon_slave address address Input 3
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave writedata writedata Input 32
add_interface_port avalon_slave read read Input 1
add_interface_port avalon_slave readdata readdata Output 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_chroma_source
# 
add_interface avalon_chroma_source avalon_streaming start
set_interface_property avalon_chroma_source associatedClock clock
set_interface_property avalon_chroma_source associatedReset reset
set_interface_property avalon_chroma_source dataBitsPerSymbol 10
set_interface_property avalon_chroma_source errorDescriptor ""
set_interface_property avalon_chroma_source firstSymbolInHighOrderBits true
set_interface_property avalon_chroma_source maxChannel 0
set_interface_property avalon_chroma_source readyLatency 0
set_interface_property avalon_chroma_source ENABLED true
set_interface_property avalon_chroma_source EXPORT_OF ""
set_interface_property avalon_chroma_source PORT_NAME_MAP ""
set_interface_property avalon_chroma_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_chroma_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_chroma_source output_data data Output 30
add_interface_port avalon_chroma_source output_empty empty Output 2
add_interface_port avalon_chroma_source output_ready ready Input 1
add_interface_port avalon_chroma_source output_startofpacket startofpacket Output 1
add_interface_port avalon_chroma_source output_valid valid Output 1
add_interface_port avalon_chroma_source output_endofpacket endofpacket Output 1

